base_url = "https://cca.codes"
title = "Creative Coding Amsterdam"

compile_sass = true
build_search_index = false
minify_html = false
generate_feeds = true

[extra]
# Put all your custom variables here
